### ISSUE TITLE
The plugin doesn't detect allready generated chunks.

### ISSUE THREAD

**Issue by KoxSosen** [pop4959/Stress#3]
![image](https://user-images.githubusercontent.com/67807644/98271489-48ad4a00-1f90-11eb-86ca-842ed60b5ad5.png)

The world is pregenerated from 5000x to 5000y.

**Comment by KoxSosen** [comment]
![image](https://user-images.githubusercontent.com/67807644/98271622-69759f80-1f90-11eb-96ca-fbc230ff6c2a.png)

**Comment by pop4959** [comment]
You need to generate chunks in that region before you can load them. You can do this by running the chunk gen test before running that command. This is a requirement of that specific test to ensure accuracy of the data being measured.

Keep in mind rx and ry are **region** coordinates, not block nor chunk coordinates. That means in your case the command is looking at the area between 256511 <= x <= 256000 to 256511 <= z <= 256000 blocks.

Read more here: https://github.com/pop4959/Stress/wiki/Tests#chunk-load
